Added Multiple Pages
smaranjitghose/img_ai_app_boilerplate pull request #15
Opened 2020-10-06 20:04 UTC by ThenoobMario

#9 

Added multiple pages with Firebase support to store user feedback, along with a Feedback.MD guide which walks through the process of setting up Firebase in the app. 

Also grouped the already existing guides into its own dedicated folder for easy navigation.

2020-10-06 20:11 UTC, smaranjitghose requested changes

2020-10-06 20:11 UTC, smaranjitghose commented on README.md
> +        - [Microsoft Azure](.Guides/Microsoft_Azure_Guide.MD)
The path would be  starting with ``./``

2020-10-06 20:11 UTC, smaranjitghose commented on app.py
> +
Nice work!

2020-10-06 20:11 UTC, smaranjitghose commented on feedback_db.py
> +
Transfer this to the file I sent you over gitter

2020-10-06 20:11 UTC, smaranjitghose commented on send_img.py
> +"storageBucket" :     ,
This file is no more required

2020-10-07 05:39 UTC, ThenoobMario commented on app.py
> +
Thank you 😃

2020-10-07 05:42 UTC, ThenoobMario commented
Made all the changes which were asked for and also resolved the conflicts.

2020-10-07 06:10 UTC, smaranjitghose approved these changes

2020-10-07 06:10 UTC, merged

2020-10-07 06:14 UTC, smaranjitghose commented
give @ThenoobMario 75 points